branches:
  - main
  - name: beta
    channel: beta
    prerelease: beta
  - name: alpha
    channel: alpha
    prerelease: alpha
  - "+([0-9])?(.{+([0-9]),x}).x"

plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
      parserOpts:
        noteKeywords:
          - BREAKING
          - BREAKING CHANGE
          - BREAKING CHANGES
      releaseRules:
        - type: build
          release: patch
        - type: chore
          release: false
        - type: ci
          release: patch
        - type: doc
          release: patch
        - type: docs
          release: patch
        - type: hotfix
          release: patch
        - type: perf
          release: patch
        - type: refactor
          release: false
        - type: revert
          release: patch
        - type: style
          release: false
        - type: test
          release: false
  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
      parserOpts:
        noteKeywords:
          - BREAKING
          - BREAKING CHANGE
          - BREAKING CHANGES
      presetConfig:
        types:
          - type: fix
            section: "Bug Fixes"
          - type: hotfix
            section: "Bug Fixes"
          - type: feat
            section: "Features"
          - type: build
            section: "CI/CD"
          - type: ci
            section: "CI/CD"
          - type: doc
            section: "Docs"
          - type: docs
            section: "Docs"
          - type: perf
            section: "Performance"
          - type: revert
            section: "Reverts"
          - type: refactor
            section: "Refactor"
            hidden: true
          - type: style
            section: "Style"
            hidden: true
          - type: test
            section: "Tests"
            hidden: true
          - type: chore
            section: "Other"
            hidden: true
  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md
      changelogTitle: "# Changelog"
  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
      message: "chore(release): ${nextRelease.version} [skip ci]"
  - "@semantic-release/github"
